export const ACTION_TYPE = {
	GET_PROVINCE: 'GET_PROVINCE',
	GET_LOCAL_STORAGE_PROVINCE: 'GET_LOCAL_STORAGE_PROVINCE',

	GET_CROPS: 'GET_CROPS',
	GET_LOCAL_STORAGE_CROPS: 'GET_LOCAL_STORAGE_CROPS',

	GET_SEASON: 'GET_SEASON',
	GET_LOCAL_STORAGE_SEASON: 'GET_LOCAL_STORAGE_SEASON',

	GET_CLIENTS: 'GET_CLIENTS',
	GET_LOCAL_STORAGE_CLIENT: 'GET_LOCAL_STORAGE_CLIENT',
}
