export const ACTION_TYPE = {
	GET_PROVINCE: 'GET_PROVINCE',
	GET_LOCAL_STORAGE_PROVINCE: 'GET_LOCAL_STORAGE_PROVINCE',

	GET_CHANNEL_PARTNERS: 'GET_CHANNEL_PARTNERS',
	GET_LOCAL_STORAGE_CHNNAEL_PARTNER: 'GET_LOCAL_STORAGE_CHNNAEL_PARTNER',

	GET_COMPANY: 'GET_COMPANY',
	GET_LOCAL_STORAGE_COMPANY: 'GET_LOCAL_STORAGE_COMPANY',

	GET_CROPS: 'GET_CROPS',
	GET_LOCAL_STORAGE_CROPS: 'GET_LOCAL_STORAGE_CROPS',

	GET_SEASON: 'GET_SEASON',
	GET_LOCAL_STORAGE_SEASON: 'GET_LOCAL_STORAGE_SEASON',

	GET_CLIENTS: 'GET_CLIENTS',
	GET_LOCAL_STORAGE_CLIENT: 'GET_LOCAL_STORAGE_CLIENT',
	GET_LOCAL_STORAGE_DOWNLOADED_CLIENT: 'GET_LOCAL_STORAGE_DOWNLOADED_CLIENT',
	GET_DNL_LOCAL_CLIENT: 'GET_DNL_LOCAL_CLIENT',

	GET_DISTRICTS: 'GET_DIGET_CHANNEL_PARTNERSSTRICTS',
	GET_LOCAL_STORAGE_DISTRICT: 'GET_LOCAL_STORAGE_DISTRICT',

	GET_COOPS: 'GET_COOPS',
	GET_LOCAL_STORAGE_COOP: 'GET_LOCAL_STORAGE_COOP',
	GET_LOCAL_STORAGE_DOWNLOADED_COOP: 'GET_LOCAL_STORAGE_DOWNLOADED_COOP',
	GET_DNL_LOCAL_COOP: 'GET_DNL_LOCAL_COOP',
}
