export const clientDetailInfoMap = {
	postalCode: 'Postal code',
	lastName: 'Last name',
	firstName: 'First name',
	registrationNumber: 'Registration number',
	vatNumber: 'VAT number',
	title: 'Title',
	initials: 'Initials',
	dateOfBirth: 'Date of Birth',
	occupation: 'Occupation',
	idNumber: 'Id number',
	channelPartner: 'Channel partner',
	email: 'Email',
	district: 'District',
	province: 'Province',
	ethnicGroup: 'Ethnic group',
	contactMethod: 'Contact method',
	mobile: 'Mobile Number',
	physAddress: 'Physical address',
	city: 'City',
	city: 'City',
	mobileMoney: 'Mobile money number',
	insuranceCompany: 'Insurance Company',
	gender: 'Gender',
}

export const coopDetailInfoMap = {
	tradingName: 'Trading name',
	postalCode: 'Postal code',
	lastName: 'Last name',
	firstName: 'First name',
	registrationNumber: 'Registration number',
	vatNumber: 'VAT number',
	title: 'Title',
	email: 'Email',
	district: 'District',
	province: 'Province',
	contactMethod: 'Contact method',
	mobile: 'Mobile',
	physAddress: 'Physical address',
	city: 'City',
	mobileMoneyNumber: 'Mobile money number',
	mobile: 'Mobile Number',
}
